/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author RH
 */
public class MainMENU extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public MainMENU() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        viewGerbong = new javax.swing.JTextArea();
        searchIDG = new javax.swing.JTextField();
        BtnsearchG = new javax.swing.JButton();
        BtnrefreshG = new javax.swing.JButton();
        BtnExitG = new javax.swing.JButton();
        BtnviewDataG = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        viewKereta = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        searchIDK = new javax.swing.JTextField();
        BtnsearchK = new javax.swing.JButton();
        BtnrefreshK = new javax.swing.JButton();
        BtnviewDataK = new javax.swing.JButton();
        BtnExitK = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        viewStasiun1 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        searchIDS = new javax.swing.JTextField();
        BtnsearchS = new javax.swing.JButton();
        BtnrefreshS = new javax.swing.JButton();
        BtnviewDataS = new javax.swing.JButton();
        BtnExitS = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        viewRute = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        searchIDR = new javax.swing.JTextField();
        BtnsearchR = new javax.swing.JButton();
        BtnrefreshR = new javax.swing.JButton();
        BtnviewDataR = new javax.swing.JButton();
        BtnExitR = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        getNama = new javax.swing.JTextField();
        getNoktp = new javax.swing.JTextField();
        jenisK = new javax.swing.JComboBox<>();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        hapusT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        viewGerbong.setColumns(20);
        viewGerbong.setRows(5);
        jScrollPane1.setViewportView(viewGerbong);

        BtnsearchG.setText("Search");

        BtnrefreshG.setText("Refresh");

        BtnExitG.setText("Exit");

        BtnviewDataG.setText("View Data");
        BtnviewDataG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnviewDataGActionPerformed(evt);
            }
        });

        jLabel1.setText("Search Data By ID");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(BtnviewDataG)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BtnExitG))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(BtnrefreshG)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(searchIDG, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(BtnsearchG, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 47, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(79, 79, 79))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchIDG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnsearchG))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnrefreshG)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 246, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnExitG)
                    .addComponent(BtnviewDataG))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1))
        );

        jTabbedPane1.addTab("Menu Gerbong", jPanel1);

        viewKereta.setColumns(20);
        viewKereta.setRows(5);
        jScrollPane2.setViewportView(viewKereta);

        jLabel2.setText("Search Data By ID");

        searchIDK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchIDKActionPerformed(evt);
            }
        });

        BtnsearchK.setText("Search");

        BtnrefreshK.setText("Refresh");

        BtnviewDataK.setText("View Data");
        BtnviewDataK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnviewDataKActionPerformed(evt);
            }
        });

        BtnExitK.setText("Exit");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(BtnviewDataK)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BtnExitK)
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(89, 89, 89))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(searchIDK, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BtnrefreshK))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BtnsearchK, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(30, 30, 30))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnsearchK)
                            .addComponent(searchIDK, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnrefreshK)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnExitK)
                            .addComponent(BtnviewDataK))))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Menu Kereta", jPanel2);

        viewStasiun1.setColumns(20);
        viewStasiun1.setRows(5);
        jScrollPane3.setViewportView(viewStasiun1);

        jLabel3.setText("Search Data By ID");

        searchIDS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchIDSActionPerformed(evt);
            }
        });

        BtnsearchS.setText("Search");

        BtnrefreshS.setText("Refresh");

        BtnviewDataS.setText("View Data");
        BtnviewDataS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnviewDataSActionPerformed(evt);
            }
        });

        BtnExitS.setText("Exit");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                    .addGap(131, 131, 131)
                                    .addComponent(BtnrefreshS))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(BtnviewDataS)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addComponent(searchIDS, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(BtnsearchS, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(0, 0, Short.MAX_VALUE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(169, 169, 169)
                            .addComponent(BtnExitS)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BtnsearchS)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(searchIDS, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)))
                        .addComponent(BtnrefreshS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnExitS)
                            .addComponent(BtnviewDataS)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE))
                .addGap(31, 31, 31))
        );

        jTabbedPane1.addTab("Menu Stasiun", jPanel3);

        viewRute.setColumns(20);
        viewRute.setRows(5);
        jScrollPane4.setViewportView(viewRute);

        jLabel4.setText("Search Data By ID");

        searchIDR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchIDRActionPerformed(evt);
            }
        });

        BtnsearchR.setText("Search");

        BtnrefreshR.setText("Refresh");

        BtnviewDataR.setText("View Data");
        BtnviewDataR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnviewDataRActionPerformed(evt);
            }
        });

        BtnExitR.setText("Exit");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                    .addGap(131, 131, 131)
                                    .addComponent(BtnrefreshR))
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(BtnviewDataR)
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                            .addComponent(searchIDR, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(BtnsearchR, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(0, 0, Short.MAX_VALUE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(169, 169, 169)
                            .addComponent(BtnExitR)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BtnsearchR)
                            .addComponent(searchIDR, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addComponent(BtnrefreshR)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnExitR)
                            .addComponent(BtnviewDataR)))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Menu Rute", jPanel4);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane5.setViewportView(jTextArea1);

        jenisK.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Eksekutif", "Ekonomi", "Bisnis", " " }));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Padalarang - Bandung", "Bandung - Cimahi", "Bandung - Kiaracondong", "Bandung - Jawa", "Jawa - Bandung", " ", " " }));

        jButton1.setText("Tambah Tiket");

        jButton2.setText("Refresh");

        hapusT.setText("Hapus Data");
        hapusT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(getNama, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                                .addComponent(getNoktp))
                            .addComponent(jenisK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(43, 43, 43))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                        .addComponent(hapusT)
                        .addGap(51, 51, 51))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(getNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jenisK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(getNoktp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButton1)))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hapusT))
                .addContainerGap(198, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Menu Tiket", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnviewDataGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnviewDataGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnviewDataGActionPerformed

    private void BtnviewDataKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnviewDataKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnviewDataKActionPerformed

    private void searchIDKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchIDKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchIDKActionPerformed

    private void searchIDSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchIDSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchIDSActionPerformed

    private void BtnviewDataSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnviewDataSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnviewDataSActionPerformed

    private void searchIDRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchIDRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchIDRActionPerformed

    private void BtnviewDataRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnviewDataRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnviewDataRActionPerformed

    private void hapusTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hapusTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMENU().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnExitG;
    private javax.swing.JButton BtnExitK;
    private javax.swing.JButton BtnExitR;
    private javax.swing.JButton BtnExitS;
    private javax.swing.JButton BtnrefreshG;
    private javax.swing.JButton BtnrefreshK;
    private javax.swing.JButton BtnrefreshR;
    private javax.swing.JButton BtnrefreshS;
    private javax.swing.JButton BtnsearchG;
    private javax.swing.JButton BtnsearchK;
    private javax.swing.JButton BtnsearchR;
    private javax.swing.JButton BtnsearchS;
    private javax.swing.JButton BtnviewDataG;
    private javax.swing.JButton BtnviewDataK;
    private javax.swing.JButton BtnviewDataR;
    private javax.swing.JButton BtnviewDataS;
    private javax.swing.JTextField getNama;
    private javax.swing.JTextField getNoktp;
    private javax.swing.JButton hapusT;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JComboBox<String> jenisK;
    private javax.swing.JTextField searchIDG;
    private javax.swing.JTextField searchIDK;
    private javax.swing.JTextField searchIDR;
    private javax.swing.JTextField searchIDS;
    private javax.swing.JTextArea viewGerbong;
    private javax.swing.JTextArea viewKereta;
    private javax.swing.JTextArea viewRute;
    private javax.swing.JTextArea viewStasiun1;
    // End of variables declaration//GEN-END:variables
    
    public void addListener(ActionListener e) {
        BtnExitG.addActionListener(e);
        BtnExitK.addActionListener(e);
        BtnExitR.addActionListener(e);
        BtnExitS.addActionListener(e);
        BtnrefreshK.addActionListener(e);
        BtnrefreshG.addActionListener(e);
        BtnrefreshR.addActionListener(e);
        BtnrefreshS.addActionListener(e);
        BtnviewDataG.addActionListener(e);
        BtnviewDataK.addActionListener(e);
        BtnviewDataR.addActionListener(e);
        BtnviewDataS.addActionListener(e);
        BtnsearchG.addActionListener(e);
        BtnsearchK.addActionListener(e);
        BtnsearchR.addActionListener(e);
        BtnsearchS.addActionListener(e);
        
    }

    public JButton getBtnExitG() {
        return BtnExitG;
    }

    public void setBtnExitG(JButton BtnExitG) {
        this.BtnExitG = BtnExitG;
    }

    public JButton getBtnrefreshG() {
        return BtnrefreshG;
    }

    public void setBtnrefreshG(JButton BtnrefreshG) {
        this.BtnrefreshG = BtnrefreshG;
    }

    public JButton getBtnsearchG() {
        return BtnsearchG;
    }

    public void setBtnsearchG(JButton BtnsearchG) {
        this.BtnsearchG = BtnsearchG;
    }

    public JButton getBtnviewDataG() {
        return BtnviewDataG;
    }

    public void setBtnviewDataG(JButton BtnviewDataG) {
        this.BtnviewDataG = BtnviewDataG;
    }

    public JButton getBtnExitK() {
        return BtnExitK;
    }

    public void setBtnExitK(JButton BtnExitK) {
        this.BtnExitK = BtnExitK;
    }

    public JButton getBtnExitR() {
        return BtnExitR;
    }

    public void setBtnExitR(JButton BtnExitR) {
        this.BtnExitR = BtnExitR;
    }

    public JButton getBtnExitS() {
        return BtnExitS;
    }

    public void setBtnExitS(JButton BtnExitS) {
        this.BtnExitS = BtnExitS;
    }

    public JButton getBtnrefreshK() {
        return BtnrefreshK;
    }

    public void setBtnrefreshK(JButton BtnrefreshK) {
        this.BtnrefreshK = BtnrefreshK;
    }

    public JButton getBtnrefreshR() {
        return BtnrefreshR;
    }

    public void setBtnrefreshR(JButton BtnrefreshR) {
        this.BtnrefreshR = BtnrefreshR;
    }

    public JButton getBtnrefreshS() {
        return BtnrefreshS;
    }

    public void setBtnrefreshS(JButton BtnrefreshS) {
        this.BtnrefreshS = BtnrefreshS;
    }

    public JButton getBtnsearchK() {
        return BtnsearchK;
    }

    public void setBtnsearchK(JButton BtnsearchK) {
        this.BtnsearchK = BtnsearchK;
    }

    public JButton getBtnsearchR() {
        return BtnsearchR;
    }

    public void setBtnsearchR(JButton BtnsearchR) {
        this.BtnsearchR = BtnsearchR;
    }

    public JButton getBtnsearchS() {
        return BtnsearchS;
    }

    public void setBtnsearchS(JButton BtnsearchS) {
        this.BtnsearchS = BtnsearchS;
    }

    public JButton getBtnviewDataK() {
        return BtnviewDataK;
    }

    public void setBtnviewDataK(JButton BtnviewDataK) {
        this.BtnviewDataK = BtnviewDataK;
    }

    public JButton getBtnviewDataR() {
        return BtnviewDataR;
    }

    public void setBtnviewDataR(JButton BtnviewDataR) {
        this.BtnviewDataR = BtnviewDataR;
    }

    public JButton getBtnviewDataS() {
        return BtnviewDataS;
    }

    public void setBtnviewDataS(JButton BtnviewDataS) {
        this.BtnviewDataS = BtnviewDataS;
    }
    
    
    
}
